"""Build notebooks 05 and 06 using nbf."""

import nbformat as nbf

# Notebook 05
nb5 = nbf.v4.new_notebook()
nb5.cells = [
    nbf.v4.new_markdown_cell('# Phase 6: Statistical Diagnostics & Feature Quality Audit\n\n## Project: Credit Risk Modelling & Independent Model Validation\n**Target Role**: Quantitative Risk Analytics / Credit Risk Model Validation\n\n### Scope of Notebook\n- Part 1: Data Preparation & Target Definition\n- Part 2: Comprehensive Descriptive Statistics\n- Part 3: Normality Diagnostics (Shapiro-Wilk, Jarque-Bera, Anderson-Darling, D\'Agostino K²)\n- Part 4: Multicollinearity Audit (Correlation, VIF, Condition Index)\n- Part 10: Categorical Variable Encoding Strategy\n- Part 11: Feature Stability (PSI/CSI)'),
    nbf.v4.new_code_cell('import sys\nimport os\nfrom pathlib import Path\nimport numpy as np\nimport pandas as pd\n\nsys.path.append(str(Path.cwd().parent / "src"))\n\nfrom validation.statistical_tests import (\n    calculate_descriptive_stats,\n    run_normality_tests,\n    generate_normality_plots,\n    calculate_csi,\n)\nfrom validation.econometrics import (\n    calculate_correlations,\n    find_high_correlations,\n    calculate_vif_and_tolerance,\n    calculate_condition_index_and_vdp,\n)\n\npd.set_option("display.max_columns", 30)\nprint("Validation modules loaded successfully!")'),
    nbf.v4.new_code_cell('data_path = Path.cwd().parent / "data" / "processed" / "accepted_2007_to_2018Q4_feature_engineered.csv.gz"\ncols_to_use = [\n    "loan_status", "issue_d", "loan_amnt", "int_rate", "installment", "annual_inc",\n    "dti", "fico_range_low", "revol_util", "delinq_2yrs", "inq_last_6mths",\n    "open_acc", "pub_rec", "revol_bal", "total_acc", "grade", "term",\n    "home_ownership", "verification_status", "purpose",\n    "fe_loan_to_income_ratio", "fe_monthly_installment_to_income_ratio",\n    "fe_credit_utilization", "fe_available_revolving_credit", "fe_credit_exposure",\n    "fe_debt_burden", "fe_credit_history_months"\n]\ndf = pd.read_csv(data_path, usecols=cols_to_use, nrows=100000, low_memory=False)\n\nbad_statuses = ["Charged Off", "Default", "Does not meet the credit policy. Status:Charged Off", "Late (31-120 days)"]\ngood_statuses = ["Fully Paid", "Does not meet the credit policy. Status:Fully Paid"]\ndf["target"] = np.nan\ndf.loc[df["loan_status"].isin(bad_statuses), "target"] = 1.0\ndf.loc[df["loan_status"].isin(good_statuses), "target"] = 0.0\n\ndf_model = df.dropna(subset=["target"]).copy()\nprint(f"Binary dataset size: {len(df_model):,}, Default Rate: {df_model[\'target\'].mean():.4%}")'),
    nbf.v4.new_code_cell('numeric_features = [\n    "loan_amnt", "int_rate", "installment", "annual_inc", "dti", "fico_range_low",\n    "revol_util", "delinq_2yrs", "inq_last_6mths", "open_acc", "pub_rec", "revol_bal",\n    "total_acc", "fe_loan_to_income_ratio", "fe_monthly_installment_to_income_ratio",\n    "fe_credit_utilization", "fe_available_revolving_credit", "fe_credit_exposure",\n    "fe_debt_burden", "fe_credit_history_months"\n]\ndesc_table = calculate_descriptive_stats(df_model, numeric_features)\ndesc_table'),
    nbf.v4.new_code_cell('norm_results = run_normality_tests(df_model, numeric_features[:10])\nnorm_results'),
    nbf.v4.new_code_cell('vif_table = calculate_vif_and_tolerance(df_model, numeric_features[:12])\nprint("VIF & Tolerance:")\nprint(vif_table)\n\nci_table, _ = calculate_condition_index_and_vdp(df_model, numeric_features[:10])\nprint("Condition Index:")\nprint(ci_table)'),
    nbf.v4.new_code_cell('df["year"] = pd.to_datetime(df["issue_d"], format="%b-%Y", errors="coerce").dt.year\nc2015 = df[df["year"] == 2015]\nc2018 = df[df["year"] == 2018]\ncsi_table = calculate_csi(c2015, c2018, numeric_features[:10])\ncsi_table')
]
with open('notebooks/05_Statistical_Diagnostics.ipynb', 'w', encoding='utf-8') as f:
    nbf.write(nb5, f)

# Notebook 06
nb6 = nbf.v4.new_notebook()
nb6.cells = [
    nbf.v4.new_markdown_cell('# Phase 6: Econometric Analysis & Model Assumption Audit\n\n## Project: Credit Risk Modelling & Independent Model Validation\n**Target Role**: Quantitative Risk Analytics / Credit Risk Model Validation\n\n### Scope of Notebook\n- Part 5: Heteroskedasticity Tests & Robust Covariance (Breusch-Pagan, White, Goldfeld-Quandt, HC3 SEs)\n- Part 6: Autocorrelation Analysis (Durbin-Watson, Breusch-Godfrey)\n- Part 7: Linearity Diagnostics (Box-Tidwell, LOWESS, Partial Residuals)\n- Part 8: Outlier & Influence Diagnostics (Hat values, Cook\'s D, Studentized Residuals)\n- Part 9: Endogeneity & IV/2SLS Evaluation Framework'),
    nbf.v4.new_code_cell('import sys\nimport json\nfrom pathlib import Path\nimport numpy as np\nimport pandas as pd\n\nsys.path.append(str(Path.cwd().parent / "src"))\n\nfrom validation.econometrics import (\n    run_heteroskedasticity_tests,\n    run_autocorrelation_tests,\n    evaluate_endogeneity_framework,\n)\nfrom validation.diagnostics import (\n    run_box_tidwell_test,\n    calculate_outlier_influence_metrics,\n)\n\npd.set_option("display.max_columns", 30)\nprint("Econometric validation modules loaded successfully!")'),
    nbf.v4.new_code_cell('data_path = Path.cwd().parent / "data" / "processed" / "accepted_2007_to_2018Q4_feature_engineered.csv.gz"\ncols_to_use = [\n    "loan_status", "issue_d", "loan_amnt", "int_rate", "installment", "annual_inc",\n    "dti", "fico_range_low", "revol_util", "delinq_2yrs", "inq_last_6mths",\n    "open_acc", "pub_rec", "revol_bal", "total_acc",\n    "fe_loan_to_income_ratio", "fe_monthly_installment_to_income_ratio",\n    "fe_credit_utilization", "fe_available_revolving_credit", "fe_credit_exposure",\n    "fe_debt_burden", "fe_credit_history_months"\n]\ndf = pd.read_csv(data_path, usecols=cols_to_use, nrows=100000, low_memory=False)\n\nbad_statuses = ["Charged Off", "Default", "Does not meet the credit policy. Status:Charged Off", "Late (31-120 days)"]\ngood_statuses = ["Fully Paid", "Does not meet the credit policy. Status:Fully Paid"]\ndf["target"] = np.nan\ndf.loc[df["loan_status"].isin(bad_statuses), "target"] = 1.0\ndf.loc[df["loan_status"].isin(good_statuses), "target"] = 0.0\n\ndf_model = df.dropna(subset=["target"]).copy()\nprint(f"Binary dataset size for Econometrics: {len(df_model):,}")'),
    nbf.v4.new_code_cell('numeric_features = ["loan_amnt", "int_rate", "installment", "annual_inc", "dti", "fico_range_low", "revol_util", "delinq_2yrs"]\nhet_summary, hc3_table = run_heteroskedasticity_tests(df_model, "target", numeric_features)\nprint("Heteroskedasticity Summary:", het_summary)\nprint("HC3 Robust SE Table:")\nprint(hc3_table)'),
    nbf.v4.new_code_cell('ac_summary = run_autocorrelation_tests(df_model, "target", numeric_features, time_col="issue_d")\nac_summary'),
    nbf.v4.new_code_cell('box_tidwell_table = run_box_tidwell_test(df_model, "target", numeric_features)\nbox_tidwell_table'),
    nbf.v4.new_code_cell('_, influence_summary = calculate_outlier_influence_metrics(df_model, "target", numeric_features)\npd.DataFrame([influence_summary])'),
    nbf.v4.new_code_cell('endo_eval = evaluate_endogeneity_framework()\nfor k, v in endo_eval.items():\n    print(f"[{k.upper()}]: {v}")')
]
with open('notebooks/06_Econometric_Analysis.ipynb', 'w', encoding='utf-8') as f:
    nbf.write(nb6, f)

print('Both notebooks successfully created via build_notebooks.py script!')
