[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[theme]
base = "dark"
primaryColor         = "#3b82f6"
backgroundColor      = "#020b18"
secondaryBackgroundColor = "#071e36"
textColor            = "#f1f5f9"
font                 = "sans serif"
